basePath: /api
definitions:
  kasir-api_internal_models.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  kasir-api_internal_models.CheckoutItem:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    type: object
  kasir-api_internal_models.CheckoutRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/kasir-api_internal_models.CheckoutItem'
        type: array
    type: object
  kasir-api_internal_models.Product:
    properties:
      category:
        $ref: '#/definitions/kasir-api_internal_models.Category'
      category_id:
        type: integer
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      stock:
        type: integer
    type: object
  kasir-api_internal_models.ProductBestSeller:
    properties:
      nama:
        type: string
      qty_terjual:
        type: integer
    type: object
  kasir-api_internal_models.SalesReport:
    properties:
      produk_terlaris:
        $ref: '#/definitions/kasir-api_internal_models.ProductBestSeller'
      total_revenue:
        type: integer
      total_transaksi:
        type: integer
    type: object
  kasir-api_internal_models.Transaction:
    properties:
      created_at:
        type: string
      details:
        items:
          $ref: '#/definitions/kasir-api_internal_models.TransactionDetail'
        type: array
      id:
        type: integer
      total_amount:
        type: integer
    type: object
  kasir-api_internal_models.TransactionDetail:
    properties:
      id:
        type: integer
      product_id:
        type: integer
      product_name:
        type: string
      quantity:
        type: integer
      subtotal:
        type: integer
      transaction_id:
        type: integer
    type: object
host: golang-kasir-production.up.railway.app
info:
  contact: {}
  description: API untuk aplikasi kasir sederhana
  title: Kasir API
  version: "1.0"
paths:
  /category:
    get:
      consumes:
      - application/json
      description: Get list of all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/kasir-api_internal_models.Category'
            type: array
      summary: Get all categories
      tags:
      - category
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/kasir-api_internal_models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Category'
        "400":
          description: invalid request
          schema:
            type: string
      summary: Create new category
      tags:
      - category
  /category/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Delete category
      tags:
      - category
    get:
      consumes:
      - application/json
      description: Get detail of a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Category'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Get detail category
      tags:
      - category
    put:
      consumes:
      - application/json
      description: Update an existing category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/kasir-api_internal_models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Category'
        "400":
          description: invalid request/id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Update category
      tags:
      - category
  /checkout:
    post:
      consumes:
      - application/json
      description: Create a new transaction with multiple items
      parameters:
      - description: Checkout Data
        in: body
        name: checkout
        required: true
        schema:
          $ref: '#/definitions/kasir-api_internal_models.CheckoutRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Transaction'
        "400":
          description: Invalid request body
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Create a new transaction (Checkout)
      tags:
      - transaction
  /product:
    get:
      consumes:
      - application/json
      description: Get list of all product
      parameters:
      - description: Product Name Filter
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/kasir-api_internal_models.Product'
            type: array
      summary: Get all product
      tags:
      - product
    post:
      consumes:
      - application/json
      description: Create a new product
      parameters:
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/kasir-api_internal_models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Product'
        "400":
          description: invalid request
          schema:
            type: string
      summary: Create new product
      tags:
      - product
  /product/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: product not found
          schema:
            type: string
      summary: Delete product
      tags:
      - product
    get:
      consumes:
      - application/json
      description: Get detail of a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Product'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: product not found
          schema:
            type: string
      summary: Get detail product
      tags:
      - product
    put:
      consumes:
      - application/json
      description: Update an existing product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product Data
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/kasir-api_internal_models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.Product'
        "400":
          description: invalid request/id
          schema:
            type: string
        "404":
          description: product not found
          schema:
            type: string
      summary: Update product
      tags:
      - product
  /report:
    get:
      consumes:
      - application/json
      description: Get total revenue, total transactions, and best selling product
        for a specific date range
      parameters:
      - description: Start Date (YYYY-MM-DD)
        in: query
        name: start_date
        required: true
        type: string
      - description: End Date (YYYY-MM-DD)
        in: query
        name: end_date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.SalesReport'
        "400":
          description: Invalid date format
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get sales report by date range
      tags:
      - report
  /report/hari-ini:
    get:
      consumes:
      - application/json
      description: Get total revenue, total transactions, and best selling product
        for today
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/kasir-api_internal_models.SalesReport'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Get daily sales report
      tags:
      - report
schemes:
- https
- http
swagger: "2.0"
