basePath: /api
definitions:
  models.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.Produk:
    properties:
      harga:
        type: integer
      id:
        type: integer
      nama:
        type: string
      stok:
        type: integer
    type: object
host: golang-kasir-production.up.railway.app
info:
  contact: {}
  description: API untuk aplikasi kasir sederhana
  title: Kasir API
  version: "1.0"
paths:
  /category:
    get:
      consumes:
      - application/json
      description: Get list of all categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Category'
            type: array
      summary: Get all categories
      tags:
      - category
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: invalid request
          schema:
            type: string
      summary: Create new category
      tags:
      - category
  /category/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Delete category
      tags:
      - category
    get:
      consumes:
      - application/json
      description: Get detail of a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Get detail category
      tags:
      - category
    put:
      consumes:
      - application/json
      description: Update an existing category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category Data
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/models.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Category'
        "400":
          description: invalid request/id
          schema:
            type: string
        "404":
          description: category not found
          schema:
            type: string
      summary: Update category
      tags:
      - category
  /produk:
    get:
      consumes:
      - application/json
      description: Get list of all produk
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Produk'
            type: array
      summary: Get all produk
      tags:
      - produk
    post:
      consumes:
      - application/json
      description: Create a new produk
      parameters:
      - description: Produk Data
        in: body
        name: produk
        required: true
        schema:
          $ref: '#/definitions/models.Produk'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Produk'
        "400":
          description: invalid request
          schema:
            type: string
      summary: Create new produk
      tags:
      - produk
  /produk/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a produk by ID
      parameters:
      - description: Produk ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: produk not found
          schema:
            type: string
      summary: Delete produk
      tags:
      - produk
    get:
      consumes:
      - application/json
      description: Get detail of a produk by ID
      parameters:
      - description: Produk ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Produk'
        "400":
          description: invalid id
          schema:
            type: string
        "404":
          description: produk not found
          schema:
            type: string
      summary: Get detail produk
      tags:
      - produk
    put:
      consumes:
      - application/json
      description: Update an existing produk
      parameters:
      - description: Produk ID
        in: path
        name: id
        required: true
        type: integer
      - description: Produk Data
        in: body
        name: produk
        required: true
        schema:
          $ref: '#/definitions/models.Produk'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Produk'
        "400":
          description: invalid request/id
          schema:
            type: string
        "404":
          description: produk not found
          schema:
            type: string
      summary: Update produk
      tags:
      - produk
schemes:
- https
- http
swagger: "2.0"
